services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/
    volumes:
      - ../.:/var/www
  nginx:
    image: nginx:latest
    restart: always
    working_dir: /var/www/
    ports:
      - 8000:80
    volumes:
      - ../.:/var/www
      - ./nginx:/etc/nginx/conf.d
